name: send email

on: push

jobs:
  mail:
    runs-on: ubuntu-latest

    steps:
      - name: message for email
        run: echo "hello team"

      - name: sending email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          secure: true
          username: ${{ secrets.ACCOUNT }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: Mail Check
          to: giriprakash29200@gmail.com, giriprakash.aws@gmail.com
          from: ${{ secrets.MAIL_ADDR }}
          body: |
          
            Hello Team,

            This Mail From Devops Team, Please Check the mail and reply to me.

            You are upload file in Given Repo,

            Repository: ${{github.repository}}
            Branch: ${{github.ref}}
            Commit Message: ${{github.event.head_commit.message}}
            author: ${{github.event.head_commit.author.name}}

            commit URL:
            https://github.com/${{ github.repository }}/commit/${{ github.sha }}

            Thanks & Regards,
            Devops Team
            


