name: send email
on: push

jobs:
  mail:
    runs-on: ubuntu-latest


    steps:
    - name: message for email
      run: echo "hello team"

    - name: sending email
      if: ${{ always() }}
      uses: dawidd6/action-send-mail@<REF>
      with:
        host: smtp.google.com
        port: 465
        account: ${{secrets.ACCOUNT}}
        password: ${{secrets.MAIL_PASSWORD}}
        from: ${{secrets.MAIL_ADDRESS}}
        to: giriprakash29200@gmail.com, giriprakash.aws@gmail.com
        subject: mail check
        body: mail check
        contentType: text/plain
      
